### ISSUE TITLE
Tests failing due to msguniq not being available 

### ISSUE THREAD

**Issue by takis** [django/django-box#20]
When running `time runtests35-sqlite3` one test fails, and this is the output:

```
FAIL: test_makemessages_no_settings (i18n.test_extraction.NoSettingsExtractionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.5/unittest/case.py", line 600, in run
    testMethod()
  File "/django/tests/i18n/test_extraction.py", line 723, in test_makemessages_no_settings
    self.assertNoOutput(err)
  File "/django/tests/admin_scripts/tests.py", line 203, in assertNoOutput
    self.assertEqual(len(stream), 0, "Stream should be empty: actually contains '%s'" % stream)
  File "/usr/lib/python3.5/unittest/case.py", line 820, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.5/unittest/case.py", line 813, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 96 != 0 : Stream should be empty: actually contains 'CommandError: Can't find msguniq. Make sure you have GNU gettext tools 0.15 or newer installed.
```

As it reported gettext being missing I tried installing it, to no avail:
```
apt-cache policy get text
N: Unable to locate package get text
```

Adding the optional repo in /etc/apt/sources.list and doing an update fixes it:
```
sudo vi /etc/apt/sources.list
sudo apt-get update
sudo apt-get install gettext
```

**Comment by takis** [comment]
Duplicate of issue #19.
