### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/django/tox.ini'

### ISSUE THREAD

**Issue by abhimanusharma** [django/django-box#37]
vagrant@djangobox:~$ runtests36-mysql
Traceback (most recent call last):
  File "/usr/local/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/usr/local/lib/python3.5/dist-packages/tox/session.py", line 38, in main
    config = prepare(args)
  File "/usr/local/lib/python3.5/dist-packages/tox/session.py", line 26, in prepare
    config = parseconfig(args)
  File "/usr/local/lib/python3.5/dist-packages/tox/config.py", line 229, in parseconfig
    parseini(config, inipath)
  File "/usr/local/lib/python3.5/dist-packages/tox/config.py", line 644, in __init__
    self._cfg = py.iniconfig.IniConfig(config.toxinipath)
  File "/usr/local/lib/python3.5/dist-packages/py/_iniconfig.py", line 50, in __init__
    f = open(self.path)
FileNotFoundError: [Errno 2] No such file or directory: '/django/tox.ini'

**Comment by ramiro** [comment]
Can you detail the sequence of steps you took before this?

Have you followed the steps detailed in the README?

What platform are you using?

Do you have a checkout of the Django source code in a sibling directory to the django-box directory?

Have the NFS shared folders been set up (one of them is the one which maps you Django source code checkout on the host to the `/django` directory on the VM)?

You are giving us too little information. It's hard to help you.

Please reopen this issue if you can provide any more details.
